from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 431)
        MainWindow.setMinimumSize(QtCore.QSize(261, 431))
        MainWindow.setMaximumSize(QtCore.QSize(261, 431))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("\n"
"")
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 130, 75, 23))
        self.pushButton.setStyleSheet("border-radius:8px;\n"
"background-color: rgb(0, 170, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/bitbug_favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setCheckable(True)
        self.pushButton.setChecked(True)
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setObjectName("pushButton")
        self.one = QtWidgets.QLineEdit(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(80, 10, 101, 16))
        self.one.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(207,241,237);")
        self.one.setObjectName("one")
        self.NetAccount = QtWidgets.QLabel(self.centralwidget)
        self.NetAccount.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.NetAccount.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.NetAccount.setObjectName("NetAccount")
        self.five = QtWidgets.QLineEdit(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(80, 90, 101, 16))
        self.five.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(176,224,230);")
        self.five.setObjectName("five")
        self.two = QtWidgets.QLineEdit(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(80, 30, 101, 16))
        self.two.setStyleSheet("background-color: rgb(145,168,209);\n"
"border-radius:5px;")
        self.two.setObjectName("two")
        self.four = QtWidgets.QLineEdit(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(80, 70, 101, 16))
        self.four.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(135,206,250);")
        self.four.setObjectName("four")
        self.three = QtWidgets.QLineEdit(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(80, 50, 101, 16))
        self.three.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(255,215,187);")
        self.three.setObjectName("three")
        self.NetPassword = QtWidgets.QLabel(self.centralwidget)
        self.NetPassword.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.NetPassword.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.NetPassword.setObjectName("NetPassword")
        self.ip_address = QtWidgets.QLabel(self.centralwidget)
        self.ip_address.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.ip_address.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.ip_address.setObjectName("ip_address")
        self.ip_scount = QtWidgets.QLabel(self.centralwidget)
        self.ip_scount.setGeometry(QtCore.QRect(30, 70, 31, 16))
        self.ip_scount.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.ip_scount.setObjectName("ip_scount")
        self.ip_password = QtWidgets.QLabel(self.centralwidget)
        self.ip_password.setGeometry(QtCore.QRect(30, 90, 31, 16))
        self.ip_password.setStyleSheet("background-color:rgba(255,255,255,0);")
        self.ip_password.setObjectName("ip_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -9, 261, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/1234.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 171, 221, 221))
        self.textBrowser.setStyleSheet("background-color:rgba(255,255,255,0.8);\n"
"font: 9pt \"Arial\";\n"
"border-radius:10px;")
        self.textBrowser.setObjectName("textBrowser")
        self.what_ip = QtWidgets.QLabel(self.centralwidget)
        self.what_ip.setGeometry(QtCore.QRect(20, 400, 221, 20))
        self.what_ip.setText("")
        self.what_ip.setObjectName("what_ip")
        self.label.raise_()
        self.five.raise_()
        self.one.raise_()
        self.NetAccount.raise_()
        self.three.raise_()
        self.NetPassword.raise_()
        self.ip_address.raise_()
        self.ip_scount.raise_()
        self.ip_password.raise_()
        self.four.raise_()
        self.two.raise_()
        self.pushButton.raise_()
        self.textBrowser.raise_()
        self.what_ip.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Padavan"))
        self.pushButton.setText(_translate("MainWindow", "设置"))
        self.one.setText(_translate("MainWindow", "13308349814@cqyt"))
        self.NetAccount.setText(_translate("MainWindow", "宽带账号："))
        self.five.setText(_translate("MainWindow", "admin"))
        self.two.setText(_translate("MainWindow", "012313"))
        self.four.setText(_translate("MainWindow", "admin"))
        self.three.setText(_translate("MainWindow", "192.168.123.1"))
        self.NetPassword.setText(_translate("MainWindow", "宽带密码："))
        self.ip_address.setText(_translate("MainWindow", "路由地址："))
        self.ip_scount.setText(_translate("MainWindow", "账号："))
        self.ip_password.setText(_translate("MainWindow", "密码："))

import imgs
